Repository mangrovedao/mangrove.js, pull requests merged in 2022-03, with the labels that each got.

#229 mangrove.js: v0.3.1
  packages/mangrove.js/package.json
  packages/mangrove.js/src/abis/Mangrove.json
  packages/mangrove.js/src/abis/SimpleMaker.json
  packages/mangrove.js/src/hardhatAddresses.json
Labels: [component] mangrove.js

#235 Fix: The estimateGas function triggers an error when the density is e…
  packages/mangrove.js/src/market.ts
Labels: bug

#237 Feature/test partial fail
  packages/mangrove-solidity/.env.local.example
  packages/mangrove-solidity/deploy/test_partial_fail.js
Labels: enhancement

#262 export displayedDecimals and defaultDisplayedDecimals
  packages/mangrove.js/src/index.ts
Labels: enhancement
